//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package kinjouj.sample.authadapter;

import android.content.Context;
import android.content.Intent;

public final class AuthenticatorService_
    extends AuthenticatorService
{


    private void init_() {
        mAccountAuthenticator = SampleAccountAuthenticator_.getInstance_(this);
    }

    @Override
    public void onCreate() {
        init_();
        super.onCreate();
    }

    public static AuthenticatorService_.IntentBuilder_ intent(Context context) {
        return new AuthenticatorService_.IntentBuilder_(context);
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, AuthenticatorService_.class);
        }

        public Intent get() {
            return intent_;
        }

        public AuthenticatorService_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startService(intent_);
        }

    }

}
