//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package kinjouj.sample.authadapter;

import android.app.Activity;
import android.content.Context;
import android.content.res.Resources;
import android.view.View;
import kinjouj.sample.authadapter.R.string;

public final class OAuth_
    extends OAuth
{

    private Context context_;
    private static OAuth_ instance_;

    private OAuth_(Context context) {
        context_ = context;
        init_();
    }

    public void afterSetContentView_() {
        if (!(context_ instanceof Activity)) {
            return ;
        }
    }

    /**
     * You should check that context is an activity before calling this method
     * 
     */
    public View findViewById(int id) {
        Activity activity_ = ((Activity) context_);
        return activity_.findViewById(id);
    }

    @SuppressWarnings("all")
    private void init_() {
        if (context_ instanceof Activity) {
            Activity activity = ((Activity) context_);
        }
        Resources resources_ = context_.getResources();
        clientId = resources_.getString(string.oauth_client_id);
        clientSecret = resources_.getString(string.oauth_client_secret);
    }

    public static OAuth_ getInstance_(Context context) {
        if (instance_ == null) {
            instance_ = new OAuth_(context.getApplicationContext());
        }
        return instance_;
    }

    public void rebind(Context context) {
    }

}
