//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package kinjouj.sample.authadapter;

import android.accounts.AccountManager;
import android.app.Activity;
import android.content.Context;
import android.content.res.Resources;
import android.view.View;
import kinjouj.sample.authadapter.R.string;

public final class SampleSyncAdapter_
    extends SampleSyncAdapter
{

    private Context context_;
    private static SampleSyncAdapter_ instance_;

    private SampleSyncAdapter_(Context context) {
        super(context);
        context_ = context;
        init_();
    }

    public void afterSetContentView_() {
        if (!(context_ instanceof Activity)) {
            return ;
        }
        ((Service_) service).afterSetContentView_();
    }

    /**
     * You should check that context is an activity before calling this method
     * 
     */
    public View findViewById(int id) {
        Activity activity_ = ((Activity) context_);
        return activity_.findViewById(id);
    }

    @SuppressWarnings("all")
    private void init_() {
        if (context_ instanceof Activity) {
            Activity activity = ((Activity) context_);
        }
        Resources resources_ = context_.getResources();
        mAccountType = resources_.getString(string.account_type);
        mAccountManager = ((AccountManager) context_.getSystemService(Context.ACCOUNT_SERVICE));
        service = Service_.getInstance_(context_);
    }

    public static SampleSyncAdapter_ getInstance_(Context context) {
        if (instance_ == null) {
            instance_ = new SampleSyncAdapter_(context.getApplicationContext());
        }
        return instance_;
    }

    public void rebind(Context context) {
    }

}
