//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package kinjouj.sample.authadapter;


public final class SampleContentProvider_
    extends SampleContentProvider
{


    private void init_() {
        mDBHelper = SampleDatabaseHelper_.getInstance_(getContext());
    }

    @Override
    public boolean onCreate() {
        init_();
        return super.onCreate();
    }

}
